### ISSUE TITLE
Pinned messages

### ISSUE THREAD

**Issue by lampholder** [element-hq/element-meta#1624]
There a few issues with the beta implementation:

- [x] https://github.com/vector-im/riot-web/issues/6329 - Hovering over a long pinned message can cause the timeline to correct itself harshly
- [x] https://github.com/vector-im/riot-web/issues/5958 - Pinned messages should use /room/{roomId}/event/{eventId} when it lands/is stable
- [x] https://github.com/vector-im/riot-web/issues/5871 - Pinned messages take forever to load if they were pinned a long time ago
- [x] https://github.com/vector-im/riot-web/issues/5438 - Pills get stretched when pinned
- [x] https://github.com/vector-im/riot-web/issues/5421 - Pinned images aren't pretty
- [x] https://github.com/vector-im/riot-web/issues/5405 - Pinned message thoughts
- [x] https://github.com/vector-im/riot-web/issues/5358 - Pinned messages don't seem to update in realtime
- [ ] https://github.com/vector-im/riot-web/issues/3627 - Pinned threads to replace FAQs
- [ ] https://github.com/vector-im/riot-web/issues/1774 - Welcome messages or MOTD for rooms
- [x] https://github.com/vector-im/riot-web/issues/7203 - Changing pinned messages uses mxid rather than name
- [x] https://github.com/vector-im/riot-web/issues/6635 - Redacting the state event breaks things
- [ ] vector-im/element-meta#1489 - Cannot see pinned messages before history allows you to 
- [x] https://github.com/vector-im/element-web/issues/17213
- [x] https://github.com/vector-im/element-web/issues/6926

**Comment by aaronraimist** [comment]
- [ ] vector-im/element-meta#1489 - Cannot see pinned messages before history allows you to

**Comment by HarHarLinks** [comment]
- [x] vector-im/element-web#17953 - changes in pins are only shown when witnessed live

**Comment by sascha-wi** [comment]
Where is information on how to use the lab feature?

**Comment by t3chguy** [comment]
https://github.com/element-hq/element-web/blob/develop/docs/labs.md#message-pinning-feature_pinning

**Comment by daniellekirkwood** [comment]
All items in this list have been handled, or will shortly be completed. I'm closing this issue.
